// <auto-generated />
using System;
using API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API.Data.Migrations
{
    [DbContext(typeof(TUDataContext))]
    partial class TUDataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("API.Entities.UserEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("FName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("Password")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("Salt")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("API.Entities.SAP_PriceListEntity", b =>
            {
                b.Property<int>("PriceList_Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PriceList_Id"), 1L, 1);

                b.Property<string>("PriceList_Code")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("PriceList_Name")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Item_Code")
                   .IsRequired()
                   .HasColumnType("nvarchar(max)");

                b.Property<double>("UnitPrice")
                    .IsRequired()
                    .HasColumnType("decimal(18,6)");

                b.HasKey("PriceList_Id");

                b.HasIndex("PriceList_Code")
                    .IsUnique();

                b.ToTable("SAP_PriceList");
            });

            modelBuilder.Entity("API.Entities.SAP_DeliveryNoteHeaderEntity", b =>
            {
                b.Property<int>("DN_Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DN_Id"), 1L, 1);

                b.Property<string>("DN_No")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("DN_Series")
                    .IsRequired()
                    .HasColumnType("int");

                b.Property<string>("DN_DocEntry")
                  .IsRequired()
                  .HasColumnType("int");

                b.Property<string>("DN_DocStatus")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("DN_Date")
                    .IsRequired()
                    .HasColumnType("datetime");

                b.Property<string>("DN_DueDate")
                   .IsRequired()
                   .HasColumnType("datetime");

                b.Property<string>("DN_PostingDate")
                  .IsRequired()
                  .HasColumnType("datetime");

                b.Property<string>("DN_TaxDate")
                  .IsRequired()
                  .HasColumnType("datetime");

                b.Property<string>("Cust_Code")
                   .IsRequired()
                   .HasColumnType("nvarchar(max)");

                b.Property<string>("Cust_Name")
                  .IsRequired()
                  .HasColumnType("nvarchar(max)");

                b.Property<string>("Contct_Code")
                  .IsRequired()
                  .HasColumnType("int");

                b.Property<string>("Curr_Type")
                .IsRequired()
                .HasColumnType("nvarchar(max)");

                b.Property<string>("Contct_Code")
                 .IsRequired()
                 .HasColumnType("int");

                b.Property<string>("Price_Code")
                 .IsRequired()
                 .HasColumnType("int");

                b.Property<string>("Ship_Code")
                 .IsRequired()
                 .HasColumnType("int");

                b.Property<string>("Ship_Address")
                .IsRequired()
                .HasColumnType("nvarchar(max)");

                b.Property<string>("Remarks")
                .IsRequired()
                .HasColumnType("nvarchar(max)");

                b.Property<double>("Discount")
                    .IsRequired()
                    .HasColumnType("decimal(18,6)");

                b.Property<double>("VAT")
                   .IsRequired()
                   .HasColumnType("decimal(18,6)");

                b.Property<double>("NetAmount")
                   .IsRequired()
                   .HasColumnType("decimal(18,6)");

                b.Property<double>("TotalAmount")
                   .IsRequired()
                   .HasColumnType("decimal(18,6)");

                b.Property<string>("DN_OwnerCode")
                .IsRequired()
                .HasColumnType("int");

                b.Property<string>("DN_Remarks")
                .IsRequired()
                .HasColumnType("nvarchar(max)");

                b.HasKey("DN_Id");

                b.HasIndex("DN_No")
                    .IsUnique();

                b.ToTable("SAP_DeliveryNote_Header");
            });

#pragma warning restore 612, 618
        }
    }
}
